default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: <%= ENV['USERNAME'] %>
      password: <%= ENV['PASSWORD'] %>
      host:     <%= ENV['IP'] %>

development:
  <<: sqlite3
  database: my_database_development

test:
  <<: *default
  database: db/development.sqlite3

production:
  <<: postgresql
  database: my_database_productions
